### ISSUE TITLE
TX unit not working

### ISSUE THREAD

**Issue by cgoodman1976** [dekuNukem/daytripper#15]
Hello, no matter what I try, the TX unit appears to not function. I press the button expecting a message to be sent to the RX unit and it does not register. I've charged the TX unit for about 2 hours and the amber light goes off. When I turn on the unit it blinks 6 times and then goes off. If I wave my hand after the blinking has turned off , it doesnt send a signal to the RX unit. 

When I press the button on the RX , I get a prompt back like this: 

transmitter ID: 0x0
baseline: 0mm
latest trigger: 0mm
input voltage: 0mV
power-on time: 0 minutes

I'm using a Mac Book Pro 15" 2017 edition. I also have access to a Windows 10 box as well. Both have the same issue with the RX unit. 

Please help.

**Comment by dekuNukem** [comment]
Hi:

I'm really sorry about this issue, it was discovered recently and rather caught me off guard.

I wrote a short article, including how to fix it. Please take a look here:

https://github.com/dekuNukem/daytripper/blob/master/mysterious_glitch.md

If you do manage to fix it, let me know your Tindie order number and I'll give you a partial refund for the trouble. And if that didn't work, I'll mail you a new one for free.

**Comment by cgoodman1976** [comment]
howdy! I did the instructions as you suggested and all is well. The unit is
working as expected.

Thanks!

-cg

**Comment by dekuNukem** [comment]
Great! I'll ask Tindie to give you a partial refund for the trouble. You should get it within 48 hours.

**Comment by varenc** [comment]
@dekuNukem I'd humbly recommend you make the glitch doc a bit easier to find. Maybe a link on the readme or in quick start guide?

I spent some time looking through the advanced doc and recent issues before I found it.  I suspect #18 has the same problem but it doesn't look like they found the mysterious glitch doc.  Thanks for documenting it so thoroughly!  Super interesting how such a subtle thing can cause issues.

**Comment by ringnex1** [comment]
hey varenc did your rx start working again because I had that problem but my tx worked fine if you did can help me with it

**Comment by varenc** [comment]
so I think my RX was actually working fine all along. How do you know your TX is working correctly?  Are you sure you don't have the battery contact problem that's [documented here](https://github.com/dekuNukem/daytripper/blob/master/mysterious_glitch.md)?

The RX's debug button seems to return all zeros if it's never paired/seen the TX so if you're seeing all zeros that doesn't necessarily mean the issue is with the RX.  Could be that TX is not transmitting correctly (what happened with me), or could mean that the RX for some reason isn't able to correctly receive anything, but based on my limited experience my guess is it's an TX transmission issue.

I open PR #19 to make a tiny note of this in the advanced usage guide.
