### ISSUE TITLE
broken rx

### ISSUE THREAD

**Issue by ringnex1** [dekuNukem/daytripper#18]
So im on my second rx because my first one had an error and now this one has the same error when i click the user button it says this
transmitter ID: 0x0
baseline: 0mm
latest trigger: 0mm
input voltage: 0mV
power-on time: 0 minutes
and it doesnt to  anything when i trip off the tx plz help

**Comment by varenc** [comment]
just got out my daytripper again and I'm seeing the same behavior.  I had things working fine a few months ago. What does it mean if all these values are zero?  TX also having issue it seems. 

One guess: Could this be because the static ram has been reset after being untouched for many months? Assuming the SRAM is kept alive/powered when these are being used regularly?  Could a firmware reprogram help solve this?

**Comment by varenc** [comment]
actually nvm, my issue is almost certainly this issue: https://github.com/dekuNukem/daytripper/blob/master/mysterious_glitch.md

the 0 values on the rx are a red herring I suspect. My tx's battery is definitely touching the board

**Comment by ringnex1** [comment]
Hey so I don't think my tx is the issue because I don't have the battery issue and also do you know if my new set might have got lost in shipping because it's not here yet
Sent from Yahoo Mail on Android 
 
  On Fri, Mar 27, 2020 at 2:18 AM, Chris Varenhorst<notifications@github.com> wrote:   


just got out my daytripper again and I'm seeing the same behavior. I had things working fine a few months ago. What does it mean if all these values are zero? TX also having issue it seems.

One guess: Could this be because the static ram has been reset after being untouched for many months? Assuming the SRAM is kept alive/powered when these are being used regularly? Could a firmware reprogram help solve this?
